name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  PACKAGE_NAME: mac-model-for-terminal

jobs:
  build:
    name: Build targets
    strategy:
      matrix:
        arch: [x86_64, arm64]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .build/${{ matrix.arch }}-apple-macosx
          key: build-${{ matrix.arch }}-${{ hashFiles('Package.swift') }}
          restore-keys: |
            build-${{ matrix.arch }}-
            build-
      - name: Build for ${{ matrix.arch }}
        run: swift build --configuration release --arch ${{ matrix.arch }} -v
      - name: Prepare products
        run: |
          mkdir -p Products
          cp -v .build/${{ matrix.arch }}-apple-macosx/release/${{ env.PACKAGE_NAME}} Products/${{ env.PACKAGE_NAME}}-${{ matrix.arch }}
      - name: Upload artifact ${{ matrix.arch }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ matrix.arch }}
          path: Products/

  deploy:
    name: Deploy to GitHub Releases
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: Products
      - name: Check files
        run: |
          ls -l Products
          ls -l Products/*
          sudo apt-get install -y tree
          tree
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "latest"
          prerelease: false
          name: "Mac Model for Terminal"
          fail_on_unmatched_files: true
          files: |
            Products/*
